package Moodel;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAF5f7NSqdMG8/E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5f7NSqdMG8/E= >>
// ----------- >>
public class Entity<IDt> {
    // ----------- << attribute.annotations@AAAAAAF5f7OhW9My+Yk= >>
    // ----------- >>
    private IDt ID;

    public IDt getID() {
        return ID;
    }

    public void setID(IDt ID) {
        this.ID = ID;
    }

// ----------- << class.extras@AAAAAAF5f7NSqdMG8/E= >>
// ----------- >>
}