package Moodel;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import Moodel.Entity;


// ----------- << imports@AAAAAAF5f7axcNM7xb0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5f7axcNM7xb0= >>
// ----------- >>
public class Moderator extends Entity<Long> {
    public Moderator(String username, String password) {
        Username = username;
        Password = password;
    }

    // ----------- << attribute.annotations@AAAAAAF5f7cagNN6YG0= >>
    // ----------- >>
    private String Username;

    // ----------- << attribute.annotations@AAAAAAF5f7cpKNOA5UE= >>
    // ----------- >>
    private String Password;

    public String getUsername() {
        return Username;
    }

    public String getPassword() {
        return Password;
    }

    public void setUsername(String Username) {
        this.Username = Username;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

// ----------- << class.extras@AAAAAAF5f7axcNM7xb0= >>
// ----------- >>
}