package Service;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import Moodel.Moderator;
import Persistance.ModeratorRepo;


// ----------- << imports@AAAAAAF5f86DQ9SGsnw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5f86DQ9SGsnw= >>
// ----------- >>
public class Service {
    // ----------- << attribute.annotations@AAAAAAF5gDiLB9eFvXE= >>
    // ----------- >>
    private ModeratorRepo ModRepository;

    // ----------- << attribute.annotations@AAAAAAF5f+ZNkNU0dDU= >>
    // ----------- >>

    public ModeratorRepo getModRepository() {
        return ModRepository;
    }


    public void setModRepository(ModeratorRepo ModRepository) {
        this.ModRepository = ModRepository;
    }




    /**
    * @param username
    */

    // ----------- << method.annotations@AAAAAAF5gEOCHtg1nwY= >>
    // ----------- >>
    public Moderator getModByName(String username) {
        return ModRepository.GetByName(username);
    }
// ----------- << class.extras@AAAAAAF5f86DQ9SGsnw= >>
// ----------- >>
}