package Persistance;/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/

import Moodel.Entity;


// ----------- << imports@AAAAAAF5f7+wutPgpVI= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAF5f7+wutPgpVI= >>
// ----------- >>
public interface Repository<ID,E extends Entity<ID>> {
    /**
    * @param X
    */

    // ----------- << method.annotations@AAAAAAF5f8TlltRW1ik= >>
    // ----------- >>
    void save(E X);
    /**
    * @param X
    */

    // ----------- << method.annotations@AAAAAAF5f8WiXdRfIwM= >>
    // ----------- >>
    void update(E X);
    /**
    * @param X
    */

    // ----------- << method.annotations@AAAAAAF5f8dNf9Rp3x4= >>
    // ----------- >>
    void delete(E X);
    // ----------- << method.annotations@AAAAAAF5f8lruNRwE7I= >>
    // ----------- >>
    Entity findOne();
    // ----------- << method.annotations@AAAAAAF5f8nwh9R8rQ8= >>
    // ----------- >>
    Iterable<E> findAll();
// ----------- << interface.extras@AAAAAAF5f7+wutPgpVI= >>
// ----------- >>
}